---
title: "Device mapping summary"
format: docx
editor: visual
execute:
  echo: false
  warning: false
---

```{r}
library(here)
library(omopgenerics)
library(dplyr)
library(OmopSketch)
library(CohortCharacteristics)
library(ggplot2)
library(visOmopResults)
library(flextable)
library(tidyr)
library(scales)

res <- importSummarisedResult(here::here("rawData"))
res <- res |> 
  mutate(cdm_name = if_else(cdm_name == "IDRIL_1", 
                            "Lancs", cdm_name))|> 
  mutate(cdm_name = if_else(cdm_name == "omop", 
                            "Barts", cdm_name))
```

## Snapshot

```{r}
visTable(res |> 
           filterSettings(result_type == "summarise_omop_snapshot"), 
         header = "cdm_name",groupColumn = "variable_name",
         hide = c("result_id", "group_level", "group_name",
                  "strata_name", "strata_level",
                  "estimate_type",
                  "variable_level",
                  "additional_name",
                  "additional_level"),
         type = "flextable") |>
  set_table_properties(width = 1, layout = "autofit")
```

\newpage

## Summary of device exposure table

```{r}
visTable(res |> 
           filterSettings(result_type == "summarise_clinical_records") |> 
           filter_out(variable_name == "Number subjects" &
                        estimate_name == "percentage") |> 
           filter(variable_name %in% 
                    c("Number subjects",
                      "Number records",
                      "Records per person")) |> 
           mutate(variable_name = factor(variable_name, 
                                         levels = c("Number subjects",
                      "Number records",
                      "Records per person"))) |> 
           arrange(variable_name) |> 
           mutate(variable_name = as.character(variable_name)), 
         header = "cdm_name",groupColumn = "variable_name",
         hide = c("result_id", "group_level", "group_name",
                  "strata_name", "strata_level",
                  "estimate_type",
                  "variable_level",
                  "additional_name",
                  "additional_level"),
         estimateName = c(
                     "N" = "<count>",
                     "Mean (SD)" = "<mean> (<sd>)",
                     "Median (min, IQR, max)" = "<median> (<min>, <q25> to <q75>, <max>)"),
         type = "flextable") |>
  set_table_properties(width = 1, layout = "autofit")
```

\newpage

## UDI and mapping to standard concept

```{r}
id_counts <- res |> 
  filterSettings(result_type == "summarise_table") |> 
  tidy() |> 
  filter(!is.na(count)) |> 
  filter(variable_name == "number records") |> 
  mutate(standard_concept = if_else(is.na(device_concept_id) | device_concept_id == "0",
                          "Unmapped",
                          "Mapped")) |> 
  mutate(has_udi = if_else(is.na(unique_device_id) | unique_device_id == "unknown",
                             "No",
                             "Yes"))

id_counts |> 
  summarise(records = sum(count), 
            .by = c(cdm_name, standard_concept, has_udi)) |> 
  left_join(
  id_counts |> 
  summarise(total = sum(count), 
            .by = c(cdm_name)),
  by = join_by(cdm_name)) |> 
  mutate(percentage = scales::percent(records / total, accuracy = 0.1)) |> 
  select(!total) |> 
  arrange(cdm_name, desc(records)) |> 
  mutate(records = scales::comma(records)) |> 
  visTable(groupColumn = "cdm_name", type = "flextable") |>
  set_table_properties(width = 1, layout = "autofit")
```

\newpage

## Trends in device records over time

```{r, echo=FALSE, warning = FALSE, message=FALSE, results = 'asis', fig.align="center", fig.width=10, fig.height=7, out.width = '90%', dpi=600}
attr(res, "settings") <- attr(res, "settings") |> 
  mutate(trend_type = case_when(
    has_uid == "TRUE" & mapped_to_standard == "TRUE" ~ "Standard concept,\nwith unique identifier",
    has_uid == "TRUE" & mapped_to_standard == "FALSE" ~ "No standard concept,\nwithout unique identifier",
    has_uid == "FALSE" & mapped_to_standard == "TRUE" ~ "Standard concept,\nwithout unique identifier",
    has_uid == "FALSE" & mapped_to_standard == "FALSE" ~ "No standard concept,\nwith unique identifier",
    .default = "All records"
  ))


plot <- plotTrend(res, 
          colour = c("trend_type"))
plot@data |> 
  ggplot() +
  geom_point(aes(time_interval, count, colour = trend_type)) +
  geom_line(aes(time_interval, count, group = trend_type, colour = trend_type)) +
  facet_grid(cdm_name ~ ., 
             scales = "free_y") +
  theme_bw() +
  ylim(c(0, NA))  +
  scale_y_continuous(labels = scales::comma) +
  theme(legend.title = element_blank(),
        legend.position = "right", 
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
  guides(colour = guide_legend(ncol = 1)) +
  xlab("") +
  ylab("Number of records")
```

\newpage

## Device concept IDs - mapped

```{r}
id_counts |> 
  arrange(desc(count)) |>
  mutate(count = scales::comma(count)) |> 
  filter(device_concept_id != "0") |> 
  visTable(groupColumn = c("cdm_name",
                           "device_concept_id",
                           "device_concept_id_name"),
           type = "flextable", hide = c("variable_name", "variable_level",
                                        "standard_concept", "has_udi")) |>
  set_table_properties(width = 1, layout = "autofit")
```

\newpage

## Device concept IDs - unmapped

```{r}
id_counts |> 
  arrange(desc(count)) |>
  mutate(count = scales::comma(count)) |> 
  filter(device_concept_id == "0") |> 
  visTable(groupColumn = c("cdm_name",
                           "device_concept_id",
                           "device_concept_id_name"),
           type = "flextable", hide = c("variable_name", "variable_level",
                                        "standard_concept", "has_udi")) |>
  set_table_properties(width = 1, layout = "autofit")
```

\newpage

## Characterisation of top 3 devices

```{r}
c_order <- res |> 
  filterSettings(result_type == "summarise_characteristics") |> 
  filter(variable_name == "Number records") |> 
  tidy() |> 
  arrange(desc(count)) |> 
  pull(cohort_name)

res |> 
  filterSettings(result_type == "summarise_characteristics") |> 
  mutate(group_level = factor(group_level, levels = c_order)) |> 
  arrange(group_level) |> 
  mutate(group_level = as.character(group_level)) |> 
  tableCharacteristics(header = c("cdm_name"), 
                     groupColumn = "cohort_name", 
           type = "flextable") |>
  set_table_properties(width = 1, layout = "autofit")
```

\newpage

```{r}
# res |> 
#   filterSettings(table_name == "procedure_occurrence") |> 
#   filter(variable_level == "-7 to 7") |> 
#   mutate(group_level = factor(group_level, levels = c_order)) |> 
#   arrange(group_level) |> 
#   mutate(group_level = as.character(group_level)) |> 
#   tableTopLargeScaleCharacteristics(, 
#            type = "flextable") |>
#   set_table_properties(width = 1, layout = "autofit")|>
#   set_caption(caption = "Most common procedure codes seen on same day as device exposure")
```

\newpage

```{r}
res |> 
  filterSettings(table_name == "condition_occurrence") |> 
  filter(variable_level == "-7 to 7") |> 
  mutate(group_level = factor(group_level, levels = c_order)) |> 
  arrange(group_level) |> 
  mutate(group_level = as.character(group_level)) |> 
  tableTopLargeScaleCharacteristics(type = "flextable") |>
  set_table_properties(width = 1, layout = "autofit")|>
  set_caption(caption = "Most common condition occurrence codes seen on same day as device exposure")
```

\newpage

```{r}
res |> 
  filterSettings(table_name == "drug_exposure") |> 
  filter(variable_level == "-7 to 7") |> 
  mutate(group_level = factor(group_level, levels = c_order)) |> 
  arrange(group_level) |> 
  mutate(group_level = as.character(group_level)) |> 
  tableTopLargeScaleCharacteristics(, 
           type = "flextable") |>
  set_table_properties(width = 1, layout = "autofit")|>
  set_caption(caption = "Most common drug exposure codes seen on same day as device exposure")
```
