# Generated by OmopViewer 0.7.0
# Be careful editing this file

server <- function(input, output, session) {
  # summary ----
  output$summary_cdm_name <- shinyTree::renderTree(summaryCdmName(data))
  output$summary_packages <- shinyTree::renderTree(summaryPackages(data))
  output$summary_min_cell_count <- shinyTree::renderTree(summaryMinCellCount(data))
  output$summary_panels <- shinyTree::renderTree(summaryPanels(data))
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      data |>
        omopgenerics::bind() |>
        omopgenerics::exportSummarisedResult(
          fileName = file, logFile = NULL, logSqlPath = NULL
        )
    }
  )
  # update buttons ----
  updateButtons <- shiny::reactiveValues(
    summarise_omop_snapshot = FALSE,
    summarise_clinical_records = FALSE,
    summarise_trend = FALSE,
    summarise_concept_id_counts = FALSE,
    summarise_characteristics = FALSE,
    summarise_large_scale_characteristics = FALSE,
    summarise_log_file = FALSE,
    summarise_table = FALSE
  )


  # summarise_omop_snapshot -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_omop_snapshot <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_omop_snapshot_cdm_name,
      input$summarise_omop_snapshot_variable_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_omop_snapshot, {
    if (updateButtons$summarise_omop_snapshot == TRUE) {
      output$update_message_summarise_omop_snapshot <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_omop_snapshot <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_omop_snapshot, {
    updateButtons$summarise_omop_snapshot <- FALSE
  })

  ## get summarise_omop_snapshot data
  getSummariseOmopSnapshotData <- shiny::eventReactive(input$update_summarise_omop_snapshot, {
    data[["summarise_omop_snapshot"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_omop_snapshot_cdm_name,
        .data$variable_name %in% input$summarise_omop_snapshot_variable_name
      )
  })
  getSummariseOmopSnapshotTable <- shiny::reactive({
    getSummariseOmopSnapshotData() |>
      OmopSketch::tableOmopSnapshot(
        header = input$summarise_omop_snapshot_table_header,
        groupColumn = input$summarise_omop_snapshot_table_group_column,
        hide = input$summarise_omop_snapshot_table_hide
      )
  })
  output$summarise_omop_snapshot_table <- gt::render_gt({
    getSummariseOmopSnapshotTable()
  })
  output$summarise_omop_snapshot_table_download <- shiny::downloadHandler(
    filename = paste0("table_snapshot.", input$summarise_omop_snapshot_table_format),
    content = function(file) {
      gt::gtsave(getSummariseOmopSnapshotTable(), file)
    }
  )

  # summarise_clinical_records -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_clinical_records <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_clinical_records_cdm_name,
      input$summarise_clinical_records_omop_table,
      input$summarise_clinical_records_variable_name,
      input$summarise_clinical_records_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_clinical_records, {
    if (updateButtons$summarise_clinical_records == TRUE) {
      output$update_message_summarise_clinical_records <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_clinical_records <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_clinical_records, {
    updateButtons$summarise_clinical_records <- FALSE
  })

  ## get summarise_clinical_records data
  getSummariseClinicalRecordsData <- shiny::eventReactive(input$update_summarise_clinical_records, {
    data[["summarise_clinical_records"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_clinical_records_cdm_name,
        .data$variable_name %in% input$summarise_clinical_records_variable_name,
        .data$estimate_name %in% input$summarise_clinical_records_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$omop_table %in% input$summarise_clinical_records_omop_table)
  })
  getSummariseClinicalRecordsTable <- shiny::reactive({
    getSummariseClinicalRecordsData() |>
      OmopSketch::tableClinicalRecords(
        header = input$summarise_clinical_records_table_header,
        groupColumn = input$summarise_clinical_records_table_group_column,
        hide = input$summarise_clinical_records_table_hide
      )
  })
  output$summarise_clinical_records_table <- gt::render_gt({
    getSummariseClinicalRecordsTable()
  })
  output$summarise_clinical_records_table_download <- shiny::downloadHandler(
    filename = paste0("table_clinical_records.", input$summarise_clinical_records_table_format),
    content = function(file) {
      gt::gtsave(getSummariseClinicalRecordsTable(), file)
    }
  )

  # summarise_trend -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_trend <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_trend_cdm_name,
      input$summarise_trend_omop_table,
      input$summarise_trend_time_interval,
      input$summarise_trend_interval,
      input$summarise_trend_type,
      input$summarise_trend_variable_name,
      input$summarise_trend_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_trend, {
    if (updateButtons$summarise_trend == TRUE) {
      output$update_message_summarise_trend <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_trend <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_trend, {
    updateButtons$summarise_trend <- FALSE
  })

  ## get summarise_trend data
  getSummariseTrendData <- shiny::eventReactive(input$update_summarise_trend, {
    data[["summarise_trend"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_trend_cdm_name,
        .data$variable_name %in% input$summarise_trend_variable_name,
        .data$estimate_name %in% input$summarise_trend_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$omop_table %in% input$summarise_trend_omop_table) |>
      omopgenerics::filterAdditional(.data$time_interval %in% input$summarise_trend_time_interval) |>
      omopgenerics::filterSettings(
        .data$interval %in% input$summarise_trend_interval,
        .data$type %in% input$summarise_trend_type
      )
  })
  getSummariseTrendTable <- shiny::reactive({
    getSummariseTrendData() |>
      OmopSketch::tableTrend(
        type = "reactable",
        header = input$summarise_trend_table_header,
        groupColumn = input$summarise_trend_table_group_column,
        hide = input$summarise_trend_table_hide
      )
  })
  output$summarise_trend_table <- reactable::renderReactable({
    getSummariseTrendTable()
  })
  output$summarise_trend_table_download <- shiny::downloadHandler(
    filename = "trends.csv",
    content = function(file) {
      getSummariseTrendTable() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseTrendPlot <- shiny::reactive({
    getSummariseTrendData() |>
      OmopSketch::plotTrend(
        output = input$summarise_trend_plot_output,
        facet = input$summarise_trend_plot_facet,
        colour = input$summarise_trend_plot_colour
      )
  })
  output$summarise_trend_plot <- shiny::renderUI({
    x <- getSummariseTrendPlot()
    renderInteractivePlot(x, input$summarise_trend_plot_interactive)
  })
  output$summarise_trend_plot_download <- shiny::downloadHandler(
    filename = "plot_trend.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseTrendPlot(),
        width = as.numeric(input$summarise_trend_plot_width),
        height = as.numeric(input$summarise_trend_plot_height),
        units = input$summarise_trend_plot_units,
        dpi = as.numeric(input$summarise_trend_plot_dpi)
      )
    }
  )

  # summarise_concept_id_counts -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_concept_id_counts <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_concept_id_counts_cdm_name,
      input$summarise_concept_id_counts_omop_table,
      input$summarise_concept_id_counts_standard_vocabulary,
      input$summarise_concept_id_counts_source_vocabulary,
      input$summarise_concept_id_counts_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_concept_id_counts, {
    if (updateButtons$summarise_concept_id_counts == TRUE) {
      output$update_message_summarise_concept_id_counts <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_concept_id_counts <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_concept_id_counts, {
    updateButtons$summarise_concept_id_counts <- FALSE
  })

  ## get summarise_concept_id_counts data
  getSummariseConceptIdCountsData <- shiny::eventReactive(input$update_summarise_concept_id_counts, {
    data[["summarise_concept_id_counts"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_concept_id_counts_cdm_name,
        .data$estimate_name %in% input$summarise_concept_id_counts_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$omop_table %in% input$summarise_concept_id_counts_omop_table) |>
      omopgenerics::filterAdditional(
        .data$standard_vocabulary %in% input$summarise_concept_id_counts_standard_vocabulary,
        .data$source_vocabulary %in% input$summarise_concept_id_counts_source_vocabulary
      )
  })
  getSummariseConceptIdCountsTidy <- shiny::reactive({
    getSummariseConceptIdCountsData() |>
      OmopSketch::tableConceptIdCounts(display = input$summarise_concept_id_counts_tidy_display)
  })
  output$summarise_concept_id_counts_tidy <- reactable::renderReactable({
    getSummariseConceptIdCountsTidy()
  })
  output$summarise_concept_id_counts_tidy_download <- shiny::downloadHandler(
    filename = "concept_id_counts.csv",
    content = function(file) {
      getSummariseConceptIdCountsTidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseConceptIdCountsTable <- shiny::reactive({
    getSummariseConceptIdCountsData() |>
      OmopSketch::tableTopConceptCounts(top = as.numeric(input$summarise_concept_id_counts_table_top))
  })
  output$summarise_concept_id_counts_table <- shiny::renderUI({
    getSummariseConceptIdCountsTable()
  })
  output$summarise_concept_id_counts_table_download <- shiny::downloadHandler(
    filename = paste0("table_top_concept_counts.", input$summarise_concept_id_counts_table_format),
    content = function(file) {
      gt::gtsave(getSummariseConceptIdCountsTable(), file)
    }
  )

  # summarise_characteristics -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_characteristics <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_characteristics_cdm_name,
      input$summarise_characteristics_cohort_name,
      input$summarise_characteristics_variable_name,
      input$summarise_characteristics_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_characteristics, {
    if (updateButtons$summarise_characteristics == TRUE) {
      output$update_message_summarise_characteristics <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_characteristics <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_characteristics, {
    updateButtons$summarise_characteristics <- FALSE
  })

  ## get summarise_characteristics data
  getSummariseCharacteristicsData <- shiny::eventReactive(input$update_summarise_characteristics, {
    data[["summarise_characteristics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_characteristics_cdm_name,
        .data$variable_name %in% input$summarise_characteristics_variable_name,
        .data$estimate_name %in% input$summarise_characteristics_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_characteristics_cohort_name)
  })
  getSummariseCharacteristicsTable <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::tableCharacteristics(
        header = input$summarise_characteristics_table_header,
        groupColumn = input$summarise_characteristics_table_group_column,
        hide = input$summarise_characteristics_table_hide
      )
  })
  output$summarise_characteristics_table <- gt::render_gt({
    getSummariseCharacteristicsTable()
  })
  output$summarise_characteristics_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_characteristics_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCharacteristicsTable(), file)
    }
  )
  getSummariseCharacteristicsPlot <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::plotCharacteristics(
        plotType = input$summarise_characteristics_plot_plot_type,
        facet = input$summarise_characteristics_plot_facet,
        colour = input$summarise_characteristics_plot_colour
      )
  })
  output$summarise_characteristics_plot <- shiny::renderUI({
    x <- getSummariseCharacteristicsPlot()
    renderInteractivePlot(x, input$summarise_characteristics_plot_interactive)
  })
  output$summarise_characteristics_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCharacteristicsPlot(),
        width = as.numeric(input$summarise_characteristics_plot_width),
        height = as.numeric(input$summarise_characteristics_plot_height),
        units = input$summarise_characteristics_plot_units,
        dpi = as.numeric(input$summarise_characteristics_plot_dpi)
      )
    }
  )

  # summarise_large_scale_characteristics -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_large_scale_characteristics <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_large_scale_characteristics_cdm_name,
      input$summarise_large_scale_characteristics_cohort_name,
      input$summarise_large_scale_characteristics_variable_level,
      input$summarise_large_scale_characteristics_analysis,
      input$summarise_large_scale_characteristics_table_name,
      input$summarise_large_scale_characteristics_type,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_large_scale_characteristics, {
    if (updateButtons$summarise_large_scale_characteristics == TRUE) {
      output$update_message_summarise_large_scale_characteristics <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_large_scale_characteristics <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_large_scale_characteristics, {
    updateButtons$summarise_large_scale_characteristics <- FALSE
  })

  ## get summarise_large_scale_characteristics data
  getSummariseLargeScaleCharacteristicsData <- shiny::eventReactive(input$update_summarise_large_scale_characteristics, {
    data[["summarise_large_scale_characteristics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_large_scale_characteristics_cdm_name,
        .data$variable_level %in% input$summarise_large_scale_characteristics_variable_level
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_large_scale_characteristics_cohort_name) |>
      omopgenerics::filterSettings(
        .data$analysis %in% input$summarise_large_scale_characteristics_analysis,
        .data$table_name %in% input$summarise_large_scale_characteristics_table_name,
        .data$type %in% input$summarise_large_scale_characteristics_type
      )
  })
  getSummariseLargeScaleCharacteristicsTableLsc <- shiny::reactive({
    if (identical(input$summarise_large_scale_characteristics_table_lsc_compare_by, "no compare")) {
      cb <- NULL
    } else {
      cb <- input$summarise_large_scale_characteristics_table_lsc_compare_by
    }
    if (identical(input$summarise_large_scale_characteristics_table_lsc_smd_reference, "no SMD")) {
      sr <- NULL
    } else {
      sr <- input$summarise_large_scale_characteristics_table_lsc_smd_reference
    }
    getSummariseLargeScaleCharacteristicsData() |>
      CohortCharacteristics::tableLargeScaleCharacteristics(
        compareBy = cb,
        hide = input$summarise_large_scale_characteristics_table_lsc_hide,
        smdReference = sr
      )
  })
  output$summarise_large_scale_characteristics_table_lsc <- reactable::renderReactable({
    getSummariseLargeScaleCharacteristicsTableLsc()
  })
  shiny::observeEvent(input$summarise_large_scale_characteristics_table_lsc_compare_by, {
    opts <- values[[paste0("summarise_large_scale_characteristics_", input$summarise_large_scale_characteristics_table_lsc_compare_by)]]
    opts <- c("no SMD", opts)
    shinyWidgets::updatePickerInput(
      inputId = "summarise_large_scale_characteristics_table_lsc_smd_reference",
      choices = opts,
      selected = "no SMD"
    )
  })
  output$summarise_large_scale_characteristics_table_lsc_download <- shiny::downloadHandler(
    filename = "smd_results.csv",
    content = function(file) {
      rt <- getSummariseLargeScaleCharacteristicsTableLsc()
      rt$x$tag$attribs$data |>
        unclass() |>
        jsonlite::fromJSON() |>
        dplyr::as_tibble() |>
        readr::write_csv(file)
    }
  )
  getSummariseLargeScaleCharacteristicsTableMostCommon <- shiny::reactive({
    getSummariseLargeScaleCharacteristicsData() |>
      CohortCharacteristics::tableTopLargeScaleCharacteristics(
        topConcepts = input$summarise_large_scale_characteristics_table_most_common_top_concepts,
        type = "gt"
      )
  })
  output$summarise_large_scale_characteristics_table_most_common <- gt::render_gt({
    getSummariseLargeScaleCharacteristicsTableMostCommon()
  })
  output$summarise_large_scale_characteristics_table_most_common_download <- shiny::downloadHandler(
    filename = paste0("top_concepts.", input$summarise_large_scale_characteristics_table_most_common_format),
    content = function(file) {
      gt::gtsave(getSummariseLargeScaleCharacteristicsTableMostCommon(), file)
    }
  )
  getSummariseLargeScaleCharacteristicsPlotCompared <- shiny::reactive({
    if (input$summarise_large_scale_characteristics_plot_compared_missings) {
      mis <- 0
    } else {
      mis <- NULL
    }
    getSummariseLargeScaleCharacteristicsData() |>
      CohortCharacteristics::plotComparedLargeScaleCharacteristics(
        colour = input$summarise_large_scale_characteristics_plot_compared_colour,
        reference = input$summarise_large_scale_characteristics_plot_compared_reference,
        facet = input$summarise_large_scale_characteristics_plot_compared_facet,
        missings = mis
      )
  })
  output$summarise_large_scale_characteristics_plot_compared <- plotly::renderPlotly({
    getSummariseLargeScaleCharacteristicsPlotCompared()
  })
  shiny::observeEvent(input$summarise_large_scale_characteristics_plot_compared_colour, {
    opts <- values[[paste0("summarise_large_scale_characteristics_", input$summarise_large_scale_characteristics_plot_compared_colour)]]
    shinyWidgets::updatePickerInput(
      inputId = "summarise_large_scale_characteristics_plot_compared_reference",
      choices = opts,
      selected = opts[1]
    )
  })

  # summarise_log_file -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_log_file <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_log_file_cdm_name,
      input$summarise_log_file_variable_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_log_file, {
    if (updateButtons$summarise_log_file == TRUE) {
      output$update_message_summarise_log_file <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_log_file <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_log_file, {
    updateButtons$summarise_log_file <- FALSE
  })

  ## get summarise_log_file data
  getSummariseLogFileData <- shiny::eventReactive(input$update_summarise_log_file, {
    data[["summarise_log_file"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_log_file_cdm_name,
        .data$variable_name %in% input$summarise_log_file_variable_name
      )
  })
  getSummariseLogFileTable <- shiny::reactive({
    getSummariseLogFileData() |>
      dplyr::filter(.data$estimate_name == "date_time") |>
      visOmopResults::visOmopTable(
        header = "cdm_name",
        hide = c("variable_level", "estimate_name")
      )
  })
  output$summarise_log_file_table <- gt::render_gt({
    getSummariseLogFileTable()
  })
  output$summarise_log_file_table_download <- shiny::downloadHandler(
    filename = paste0("table_log.", input$summarise_log_file_table_format),
    content = function(file) {
      gt::gtsave(getSummariseLogFileTable(), file)
    }
  )
  getSummariseLogFilePlot <- shiny::reactive({
    getSummariseLogFileData() |>
      dplyr::filter(.data$estimate_name == "elapsed_time") |>
      visOmopResults::barPlot(
        x = c("log_id", "variable_name"),
        y = "elapsed_time",
        colour = "cdm_name",
        position = input$summarise_log_file_plot_position
      )
  })
  output$summarise_log_file_plot <- shiny::renderUI({
    x <- getSummariseLogFilePlot()
    renderInteractivePlot(x, input$summarise_log_file_plot_interactive)
  })
  output$summarise_log_file_plot_download <- shiny::downloadHandler(
    filename = "plot_logs.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseLogFilePlot(),
        width = as.numeric(input$summarise_log_file_plot_width),
        height = as.numeric(input$summarise_log_file_plot_height),
        units = input$summarise_log_file_plot_units,
        dpi = as.numeric(input$summarise_log_file_plot_dpi)
      )
    }
  )

  # summarise_table -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_table <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_table_cdm_name,
      input$summarise_table_variable_name,
      input$summarise_table_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_table, {
    if (updateButtons$summarise_table == TRUE) {
      output$update_message_summarise_table <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_table <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_table, {
    updateButtons$summarise_table <- FALSE
  })

  ## get summarise_table data
  getSummariseTableData <- shiny::eventReactive(input$update_summarise_table, {
    data[["summarise_table"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_table_cdm_name,
        .data$variable_name %in% input$summarise_table_variable_name,
        .data$estimate_name %in% input$summarise_table_estimate_name
      )
  })
  getSummariseTableTidy <- shiny::reactive({
    tidyDT(getSummariseTableData(), input$summarise_table_tidy_columns, input$summarise_table_tidy_pivot_estimates)
  })
  output$summarise_table_tidy <- DT::renderDT({
    getSummariseTableTidy()
  })
  output$summarise_table_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseTableData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseTableTable <- shiny::reactive({
    getSummariseTableData() |>
      simpleTable(
        header = input$summarise_table_table_header,
        group = input$summarise_table_table_group_column,
        hide = input$summarise_table_table_hide
      )
  })
  output$summarise_table_table <- gt::render_gt({
    getSummariseTableTable()
  })
  output$summarise_table_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$summarise_table_table_format),
    content = function(file) {
      gt::gtsave(getSummariseTableTable(), file)
    }
  )
}
