# Generated by OmopViewer 0.7.0
# Be careful editing this file

ui <- bslib::page_navbar(
  title = shiny::tags$span(
    shiny::tags$img(
      src = "ohdsi_logo.svg",
      width = "auto",
      height = "46px",
      class = "me-3",
      alt = "logo"
    ),
    ""
  ),
  theme = bslib::bs_theme(brand = TRUE),
  shiny::tags$style(HTML(
    ".sticky-top-btn {
      position: sticky;
      top: 0;
      z-index: 20;
      background: var(--bs-body-bg);
    }"
  )),
  bslib::nav_panel(
    title = "Background",
    icon = shiny::icon("book-atlas"),
    backgroundCard("background.md")
  ),
  bslib::nav_panel(
    title = "Summary",
    icon = shiny::icon("file-alt"),
    bslib::card(
      bslib::card_header("Explore results"),
      shiny::tags$div(
        class = "mb-2",
        shinyTree::shinyTree("summary_cdm_name", theme = "proton", themeIcons = FALSE),
        shinyTree::shinyTree("summary_packages", theme = "proton", themeIcons = FALSE),
        shinyTree::shinyTree("summary_min_cell_count", theme = "proton", themeIcons = FALSE),
        shinyTree::shinyTree("summary_panels", theme = "proton", themeIcons = FALSE)
      ),
      full_screen = TRUE
    )
  ),
  bslib::nav_menu(
    title = "OmopSketch",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Snapshot",
      icon = shiny::icon("camera"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_omop_snapshot",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_omop_snapshot")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_omop_snapshot_cdm_name",
            label = "CDM name",
            choices = choices$summarise_omop_snapshot_cdm_name,
            selected = selected$summarise_omop_snapshot_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_omop_snapshot_variable_name",
            label = "Variable name",
            choices = choices$summarise_omop_snapshot_variable_name,
            selected = selected$summarise_omop_snapshot_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Snapshot",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_omop_snapshot_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_omop_snapshot_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = "estimate_name",
                      input_id = "summarise_omop_snapshot_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = "cdm_name",
                      input_id = "summarise_omop_snapshot_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = "variable_name",
                      input_id = "summarise_omop_snapshot_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = "variable_level",
                      input_id = "summarise_omop_snapshot_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_omop_snapshot_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Clinical Tables Summary",
      icon = shiny::icon("bars-staggered"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_clinical_records",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_clinical_records")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_clinical_records_cdm_name",
            label = "CDM name",
            choices = choices$summarise_clinical_records_cdm_name,
            selected = selected$summarise_clinical_records_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_clinical_records_omop_table",
            label = "Omop table",
            choices = choices$summarise_clinical_records_omop_table,
            selected = selected$summarise_clinical_records_omop_table,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_clinical_records_variable_name",
            label = "Variable name",
            choices = choices$summarise_clinical_records_variable_name,
            selected = selected$summarise_clinical_records_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_clinical_records_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_clinical_records_estimate_name,
            selected = selected$summarise_clinical_records_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Clinical records",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_clinical_records_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_clinical_records_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("variable_name", "variable_level", "estimate_name", "type_concept_id", "is_required"),
                      input_id = "summarise_clinical_records_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = "cdm_name",
                      input_id = "summarise_clinical_records_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = "omop_table",
                      input_id = "summarise_clinical_records_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = character(),
                      input_id = "summarise_clinical_records_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_clinical_records_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Trends",
      icon = shiny::icon("arrow-trend-up"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_trend",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_trend")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_trend_cdm_name",
            label = "CDM name",
            choices = choices$summarise_trend_cdm_name,
            selected = selected$summarise_trend_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_trend_omop_table",
            label = "Omop table",
            choices = choices$summarise_trend_omop_table,
            selected = selected$summarise_trend_omop_table,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_trend_time_interval",
            label = "Time interval",
            choices = choices$summarise_trend_time_interval,
            selected = selected$summarise_trend_time_interval,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_trend_interval",
            label = "Interval",
            choices = choices$summarise_trend_interval,
            selected = selected$summarise_trend_interval,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_trend_type",
            label = "Type",
            choices = choices$summarise_trend_type,
            selected = selected$summarise_trend_type,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_trend_variable_name",
            label = "Variable name",
            choices = choices$summarise_trend_variable_name,
            selected = selected$summarise_trend_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_trend_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_trend_estimate_name,
            selected = selected$summarise_trend_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Trends",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_trend_table_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("variable_name", "estimate_name", "time_interval"),
                      input_id = "summarise_trend_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = "cdm_name",
                      input_id = "summarise_trend_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = c("interval", "type", "omop_table"),
                      input_id = "summarise_trend_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = "variable_level",
                      input_id = "summarise_trend_table_hide"
                    )
                  ),
                  position = "right"
                ),
                reactable::reactableOutput("summarise_trend_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot Trends",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_trend_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_trend_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_trend_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_trend_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_trend_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_trend_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_trend_plot_output",
                    label = "Output",
                    choices = c("record", "person", "person-days", "age", "sex"),
                    selected = "record",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_trend_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "omop_table", "time_interval", "interval", "type"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_trend_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "omop_table", "time_interval", "interval", "type"),
                    selected = character(),
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_trend_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Concept Counts",
      icon = shiny::icon("database"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_concept_id_counts",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_concept_id_counts")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_concept_id_counts_cdm_name",
            label = "CDM name",
            choices = choices$summarise_concept_id_counts_cdm_name,
            selected = selected$summarise_concept_id_counts_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_concept_id_counts_omop_table",
            label = "Omop table",
            choices = choices$summarise_concept_id_counts_omop_table,
            selected = selected$summarise_concept_id_counts_omop_table,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_concept_id_counts_standard_vocabulary",
            label = "Standard vocabulary",
            choices = choices$summarise_concept_id_counts_standard_vocabulary,
            selected = selected$summarise_concept_id_counts_standard_vocabulary,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_concept_id_counts_source_vocabulary",
            label = "Source vocabulary",
            choices = choices$summarise_concept_id_counts_source_vocabulary,
            selected = selected$summarise_concept_id_counts_source_vocabulary,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_concept_id_counts_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_concept_id_counts_estimate_name,
            selected = selected$summarise_concept_id_counts_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Concept Counts",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_concept_id_counts_tidy_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_concept_id_counts_tidy_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_concept_id_counts_tidy_display",
                    label = "Display",
                    choices = c("overall", "standard", "source", "missing standard", "missing source"),
                    selected = "overall",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                reactable::reactableOutput("summarise_concept_id_counts_tidy") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Top Concept Counts",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_concept_id_counts_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_concept_id_counts_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_concept_id_counts_table_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_concept_id_counts_table_top",
                    label = "Top",
                    choices = c(5L, 10L, 50L, 100L),
                    selected = 10L,
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_concept_id_counts_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    )
  ),
  bslib::nav_menu(
    title = "CohortCharacteristics",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Cohort Characteristics",
      icon = shiny::icon("users-gear"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_characteristics",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_characteristics")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_cdm_name",
            label = "CDM name",
            choices = choices$summarise_characteristics_cdm_name,
            selected = selected$summarise_characteristics_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_cohort_name",
            label = "Cohort name",
            choices = choices$summarise_characteristics_cohort_name,
            selected = selected$summarise_characteristics_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_variable_name",
            label = "Variable name",
            choices = choices$summarise_characteristics_variable_name,
            selected = selected$summarise_characteristics_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_characteristics_estimate_name,
            selected = selected$summarise_characteristics_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Characteristics",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_characteristics_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("variable_name", "variable_level", "estimate_name"),
                      input_id = "summarise_characteristics_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = c("cdm_name", "cohort_name"),
                      input_id = "summarise_characteristics_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = character(),
                      input_id = "summarise_characteristics_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = "table_name",
                      input_id = "summarise_characteristics_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_characteristics_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot Characteristics",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_characteristics_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_characteristics_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_characteristics_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_characteristics_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_characteristics_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_plot_plot_type",
                    label = "Plot type",
                    choices = c("boxplot", "barplot", "scatterplot"),
                    selected = "boxplot",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "cohort_name"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "cohort_name"),
                    selected = "cohort_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_characteristics_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Large Scale Characteristics",
      icon = shiny::icon("arrow-up-right-dots"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_large_scale_characteristics",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_large_scale_characteristics")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_cdm_name",
            label = "CDM name",
            choices = choices$summarise_large_scale_characteristics_cdm_name,
            selected = selected$summarise_large_scale_characteristics_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_cohort_name",
            label = "Cohort name",
            choices = choices$summarise_large_scale_characteristics_cohort_name,
            selected = selected$summarise_large_scale_characteristics_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_variable_level",
            label = "Variable level",
            choices = choices$summarise_large_scale_characteristics_variable_level,
            selected = selected$summarise_large_scale_characteristics_variable_level,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_analysis",
            label = "Analysis",
            choices = choices$summarise_large_scale_characteristics_analysis,
            selected = selected$summarise_large_scale_characteristics_analysis,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_table_name",
            label = "Table name",
            choices = choices$summarise_large_scale_characteristics_table_name,
            selected = selected$summarise_large_scale_characteristics_table_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_type",
            label = "Type",
            choices = choices$summarise_large_scale_characteristics_type,
            selected = selected$summarise_large_scale_characteristics_type,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_large_scale_characteristics_table_lsc_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_table_lsc_compare_by",
                    label = "Compare by",
                    choices = c("no compare", "cdm_name", "cohort_name", "type", "variable_level"),
                    selected = "no compare",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_table_lsc_hide",
                    label = "Hide",
                    choices = c("cdm_name", "cohort_name", "type", "variable_level"),
                    selected = "type",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_table_lsc_smd_reference",
                    label = "SMD reference",
                    choices = "no SMD",
                    selected = "no SMD",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                reactable::reactableOutput("summarise_large_scale_characteristics_table_lsc") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Most common codes",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_table_most_common_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_large_scale_characteristics_table_most_common_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_table_most_common_top_concepts",
                    label = "Top concepts",
                    choices = c(10L, 25L, 100L),
                    selected = 10L,
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_large_scale_characteristics_table_most_common") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot Compared",
            bslib::card(
              full_screen = TRUE,
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_large_scale_characteristics_plot_compared_missings",
                    label = "Missing data",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_plot_compared_colour",
                    label = "Colour",
                    choices = c("cdm_name", "cohort_name", "type", "variable_level"),
                    selected = NULL,
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_plot_compared_reference",
                    label = "Reference",
                    choices = NULL,
                    selected = NULL,
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_plot_compared_facet",
                    label = "Facet",
                    choices = c("cdm_name", "cohort_name", "type", "variable_level"),
                    selected = c("cdm_name", "cohort_name"),
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                plotly::plotlyOutput("summarise_large_scale_characteristics_plot_compared") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Logs",
    icon = shiny::icon("clipboard-list"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::card(
          class = "sticky-top-btn",
          bslib::card_body(
            shiny::actionButton(
              inputId = "update_summarise_log_file",
              label = "Update content",
              width = "100%"
            ),
            uiOutput(outputId = "update_message_summarise_log_file")
          )
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_log_file_cdm_name",
          label = "CDM name",
          choices = choices$summarise_log_file_cdm_name,
          selected = selected$summarise_log_file_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_log_file_variable_name",
          label = "Variable name",
          choices = choices$summarise_log_file_variable_name,
          selected = selected$summarise_log_file_variable_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        position = "left"
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Table Logs",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "summarise_log_file_table_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "summarise_log_file_table_download", label = "Download table")
              ),
              class = "text-end"
            ),
            gt::gt_output("summarise_log_file_table") |>
              shinycssloaders::withSpinner()
          )
        ),
        bslib::nav_panel(
          title = "Plot Timing",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::numericInput(
                  inputId = "summarise_log_file_plot_width",
                  label = "Width",
                  value = 15
                ),
                shiny::numericInput(
                  inputId = "summarise_log_file_plot_height",
                  label = "Height",
                  value = 15
                ),
                shinyWidgets::pickerInput(
                  inputId = "summarise_log_file_plot_units",
                  label = "Units",
                  choices = c("px", "cm", "inch"),
                  selected = "cm",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::numericInput(
                  inputId = "summarise_log_file_plot_dpi",
                  label = "DPI",
                  value = 300
                ),
                shiny::downloadButton(outputId = "summarise_log_file_plot_download", label = "Download plot")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::materialSwitch(
                  inputId = "summarise_log_file_plot_interactive",
                  label = "Interactive",
                  value = TRUE
                ),
                shinyWidgets::pickerInput(
                  inputId = "summarise_log_file_plot_position",
                  label = "Columns",
                  choices = c("dodge", "stack"),
                  selected = "stack",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                position = "right"
              ),
              shiny::uiOutput("summarise_log_file_plot") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Summarise table",
    icon = shiny::icon("folder"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::card(
          class = "sticky-top-btn",
          bslib::card_body(
            shiny::actionButton(
              inputId = "update_summarise_table",
              label = "Update content",
              width = "100%"
            ),
            uiOutput(outputId = "update_message_summarise_table")
          )
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_table_cdm_name",
          label = "CDM name",
          choices = choices$summarise_table_cdm_name,
          selected = selected$summarise_table_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_table_variable_name",
          label = "Variable name",
          choices = choices$summarise_table_variable_name,
          selected = selected$summarise_table_variable_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_table_estimate_name",
          label = "Estimate name",
          choices = choices$summarise_table_estimate_name,
          selected = selected$summarise_table_estimate_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        position = "left"
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "summarise_table_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "summarise_table_tidy_columns",
                  label = "Columns",
                  choices = c("cdm_name", "device_concept_id", "device_concept_id_name", "device_source_concept_id", "device_source_concept_id_name", "device_source_value", "variable_name", "variable_level"),
                  selected = c("cdm_name", "device_concept_id", "device_concept_id_name", "device_source_concept_id", "device_source_concept_id_name", "device_source_value", "variable_name", "variable_level"),
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::checkboxInput(
                  inputId = "summarise_table_tidy_pivot_estimates",
                  label = "Pivot estimates",
                  value = TRUE
                ),
                position = "right"
              ),
              DT::DTOutput("summarise_table_tidy") |>
                shinycssloaders::withSpinner()
            )
          )
        ),
        bslib::nav_panel(
          title = "Table",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "summarise_table_table_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "summarise_table_table_download", label = "Download table")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                sortable::bucket_list(
                  header = NULL,
                  sortable::add_rank_list(
                    text = "None",
                    labels = c("cdm_name", "device_concept_id", "device_concept_id_name", "device_source_concept_id", "device_source_concept_id_name", "device_source_value", "variable_name", "variable_level", "estimate_name"),
                    input_id = "summarise_table_table_none"
                  ),
                  sortable::add_rank_list(
                    text = "Header",
                    labels = character(),
                    input_id = "summarise_table_table_header"
                  ),
                  sortable::add_rank_list(
                    text = "Group columns",
                    labels = character(),
                    input_id = "summarise_table_table_group_column"
                  ),
                  sortable::add_rank_list(
                    text = "Hide",
                    labels = character(),
                    input_id = "summarise_table_table_hide"
                  )
                ),
                position = "right"
              ),
              gt::gt_output("summarise_table_table") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_spacer(),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("download"),
      shiny::downloadButton(
        outputId = "download_raw",
        label = "Download raw data",
        icon = shiny::icon("download")
      )
    )
  ),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("circle-info"),
      shiny::tags$img(
        src = "hds_logo.svg",
        class = "logo-img",
        alt = "Logo",
        height = "auto",
        width = "30%",
        style = "float:right"
      ),
      "This shiny app was generated with ",
      shiny::a(
        "OmopViewer",
        href = "https://github.com/OHDSI/OmopViewer",
        target = "_blank"
      ),
      shiny::strong("v0.7.0")
    )
  ),
  bslib::nav_item(bslib::input_dark_mode(id = "dark_mode", mode = "light"))
)
